### ISSUE TITLE
Adding Image to Draw error

### ISSUE THREAD

**Issue by Ifelsethendo** [Akascape/CTkDesigner-Support#13]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 559, in _clicked
    self._command()
  File "CTkDesigner.py", line 1100, in add_path
  File "ctkdlib\custom_widgets\ctk_draw.py", line 176, in configure
    self.update()
  File "ctkdlib\custom_widgets\ctk_draw.py", line 94, in update
    image = self.saturation(image, self.sat)
  File "ctkdlib\custom_widgets\ctk_draw.py", line 83, in saturation
    return ImageEnhance.Color(img).enhance(value)
  File "PIL\ImageEnhance.py", line 36, in enhance
  File "PIL\Image.py", line 3230, in blend
ValueError: image has wrong mode
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "tkinter\__init__.py", line 814, in callit
  File "ctkdlib\custom_widgets\ctk_draw.py", line 127, in clear
    self.update()
  File "ctkdlib\custom_widgets\ctk_draw.py", line 94, in update
    image = self.saturation(image, self.sat)
  File "ctkdlib\custom_widgets\ctk_draw.py", line 83, in saturation
    return ImageEnhance.Color(img).enhance(value)
  File "PIL\ImageEnhance.py", line 36, in enhance
  File "PIL\Image.py", line 3230, in blend
ValueError: image has wrong mode

Was a black and white PNG that loads fine into a button

![64](https://github.com/Akascape/CTkDesigner-Support/assets/93362020/ac852ed7-a852-4e8f-aa80-97ab39054f9a)

**Comment by Akascape** [comment]
@Ifelsethendo Fixed, update ctkdlib to v4.2 `pip install ctkdlib --upgrade`

**Comment by Akascape** [comment]
You can change the image after exporting, changes in ctkdesigner will be implemented in next version,
