### ISSUE TITLE
Duplicate button with image error

### ISSUE THREAD

**Issue by Ifelsethendo** [Akascape/CTkDesigner-Support#14]
Chose Duplicate from menu and this happened:

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 559, in _clicked
    self._command()
  File "CTkDesigner.py", line 1100, in add_path
  File "ctkdlib\custom_widgets\ctk_draw.py", line 176, in configure
    self.update()
  File "ctkdlib\custom_widgets\ctk_draw.py", line 94, in update
    image = self.saturation(image, self.sat)
  File "ctkdlib\custom_widgets\ctk_draw.py", line 83, in saturation
    return ImageEnhance.Color(img).enhance(value)
  File "PIL\ImageEnhance.py", line 36, in enhance
  File "PIL\Image.py", line 3230, in blend
ValueError: image has wrong mode
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "tkinter\__init__.py", line 814, in callit
  File "ctkdlib\custom_widgets\ctk_draw.py", line 127, in clear
    self.update()
  File "ctkdlib\custom_widgets\ctk_draw.py", line 94, in update
    image = self.saturation(image, self.sat)
  File "ctkdlib\custom_widgets\ctk_draw.py", line 83, in saturation
    return ImageEnhance.Color(img).enhance(value)
  File "PIL\ImageEnhance.py", line 36, in enhance
  File "PIL\Image.py", line 3230, in blend
ValueError: image has wrong mode
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "CTkDesigner.py", line 519, in <lambda>
  File "CTkDesigner.py", line 656, in fix_widget
  File "CTkDesigner.py", line 459, in add_widget
  File "ctkdlib\custom_widgets\ctk_draw.py", line 50, in __init__
    self.update()
  File "ctkdlib\custom_widgets\ctk_draw.py", line 94, in update
    image = self.saturation(image, self.sat)
  File "ctkdlib\custom_widgets\ctk_draw.py", line 83, in saturation
    return ImageEnhance.Color(img).enhance(value)
  File "PIL\ImageEnhance.py", line 36, in enhance
  File "PIL\Image.py", line 3230, in blend
ValueError: image has wrong mode
customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py:179: UserWarning: CTkButton Warning: Given image is not CTkImage but <class 'str'>. Image can not be scaled on HighDPI displays, use CTkImage instead.

  warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "CTkDesigner.py", line 490, in <lambda>
  File "CTkDesigner.py", line 459, in add_widget
  File "customtkinter\windows\widgets\ctk_button.py", line 108, in __init__
    self._draw()
  File "customtkinter\windows\widgets\ctk_button.py", line 266, in _draw
    self._update_image()  # set image
  File "customtkinter\windows\widgets\ctk_button.py", line 178, in _update_image
    self._image_label.configure(image=self._image)
  File "tkinter\__init__.py", line 1646, in configure
  File "tkinter\__init__.py", line 1636, in _configure
_tkinter.TclError: image "customtkinter.CTkImage(Image.open('C:/Users/IfElseThenDo/Documents/BitMapFontEditor/SavedBinary_1/64.png'), size=(20,21))" doesn't exist

**Comment by Ifelsethendo** [comment]
The File 'C:/Users/IfElseThenDo/Documents/BitMapFontEditor/SavedBinary_1/64.png had been moved since it was placed inside the button and so threw this error on Duplicate

**Comment by Akascape** [comment]
@Ifelsethendo The file should be there in the original location, or else it will not load.
